return { -- Useful plugin to show you pending keybinds.
  'folke/which-key.nvim',
  event = 'VeryLazy',
  opts = {
    -- preset = 'helix',
    delay = 0,
    icons = {
      group = '',
      mappings = false,
    },
    -- Document existing key chains
    spec = {
      { '<leader>f', group = '[f]ind' },
      { '<leader>fw', group = '[w]ord' },
      { '<leader>fc', group = '[C]urrent' },
      { '<leader>t', group = '[t]odo' },
      { '<leader>g', group = '[g]it', mode = { 'n', 'v' } },
      { '<leader>e', group = '[e]xplore', mode = { 'n', 'v' } },
      { '<leader>m', group = '[m]arkdown' },
      { '<leader>s', group = '[s]pelling' },
      { '<leader>1', hidden = true, mode = 'n' },
      { '<leader>2', hidden = true, mode = 'n' },
      { '<leader>3', hidden = true, mode = 'n' },
      { '<leader>4', hidden = true, mode = 'n' },
      { '<leader>5', hidden = true, mode = 'n' },
      { '<leader>6', hidden = true, mode = 'n' },
      { '<leader>7', hidden = true, mode = 'n' },
      { '<leader>8', hidden = true, mode = 'n' },
      { '<leader>9', hidden = true, mode = 'n' },
      -- Renaming markdown commands
      { '<leader>mr', desc = 'create [r]ow below' },
      { '<leader>mR', desc = 'create [R]ow above' },
      { '<leader>mc', desc = 'create [c]olumn after' },
      { '<leader>mC', desc = 'create [C]olumn before' },
      { '<leader>mdr', desc = 'delete row' },
      { '<leader>mdc', desc = 'delete column' },
      { '<leader>mu', desc = 'update numbering' },
      { '<leader>mt', desc = 'create table' },
    },
  },
}
