return { -- Useful plugin to show you pending keybinds.
  'folke/which-key.nvim',
  event = 'VeryLazy',
  opts = {
    delay = 0,
    icons = {
      group = '',
      mappings = false,
    },
    -- Document existing key chains
    spec = {
      { '<leader>f', group = '[f]ind' },
      { '<leader>w', group = '[w]orkspace' },
      { '<leader>t', group = '[t]erminal' },
      { '<leader>g', group = '[g]it', mode = { 'n', 'v' } },
      { '<leader>e', group = '[e]xplore', mode = { 'n', 'v' } },
      { '<leader>m', group = '[m]arkdown' },
      { '<leader>s', group = '[s]pelling' },
      { '<leader>l', group = '[l]sp' },
      { '<leader>fw', group = '[w]ord' },
      { '<leader>fc', group = '[C]urrent' },
      { '<leader>1', hidden = true, mode = 'n' },
      { '<leader>2', hidden = true, mode = 'n' },
      { '<leader>3', hidden = true, mode = 'n' },
      { '<leader>4', hidden = true, mode = 'n' },
      { '<leader>5', hidden = true, mode = 'n' },
      { '<leader>6', hidden = true, mode = 'n' },
      { '<leader>7', hidden = true, mode = 'n' },
      { '<leader>8', hidden = true, mode = 'n' },
      { '<leader>9', hidden = true, mode = 'n' },
      -- Renaming markdown commands
      { '<leader>mt', desc = '[t]odo list' },
      { '<leader>mp', desc = '[p]aste link' },
      { '<leader>md', desc = '[d]elete link' },
      { '<leader>mm', desc = '[m]ove link' },
      { '<leader>mu', desc = '[u]pdate numbering' },
      { '<leader>mr', desc = 'create [r]ow below' },
      { '<leader>mR', desc = 'create [R]ow above' },
      { '<leader>mc', desc = 'create [c]olumn after' },
      { '<leader>mC', desc = 'create [C]olumn befor' },
    },
  },
}
